# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pw_obiegi', '0002_auto_20170924_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlowiec',
            old_name='handlowiec',
            new_name='handlowiec_name',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material',
            new_name='material_name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='status_name',
        ),
    ]
