# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_obiegi', '0003_auto_20170924_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='obieg',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
