# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_obiegi', '0007_auto_20171008_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='obieg',
            name='uwagi',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
