# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pw_obiegi', '0009_auto_20171018_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obieg',
            options={'ordering': ['-data_wprowadzenia']},
        ),
    ]
